#region List of namespaces
using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Media;
using System.Collections.Generic;
using System.Threading;
using System.Globalization; // For CultureInfo.CurrentCulture.NumberFormat.CurrencySymbol and CultureInfo.CurrentCulture.TextInfo.ToTitleCase() etc.
using System.Reflection; // For accessing project assembly info
using System.Resources; // For multi-language forms
using System.Windows.Forms;
using System.Linq; // For Controls.OfType<>()
using System.Web; // For the autogenerated temporary website code
using System.Web.UI; // For the Page class. Need to add a Reference to the System.Web framework from the solution explorer for this to work.
using System.Web.UI.WebControls; // For WebForm controls
#endregion

namespace NamespacesIUse
{
    class NameSpacesIUse
    {
        static void Main(string[] args)
        {
        }
    }
}
