/// <file>
/// <author>Hanna Sababa</author>
/// <datecreated>2016-11-19</datecreated>
/// <summary>
///  Contains the part of the class StudentDataMainForm with the autogenerated code
/// </summary>
/// </file>

namespace StudentData
{
    partial class StudentDataMainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.studentDataMainFormMenuStrip = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.showAllStudentsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.addUniversityToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.addAStudentGroupBox = new System.Windows.Forms.GroupBox();
            this.standingGroupBox = new System.Windows.Forms.GroupBox();
            this.standingLabel = new System.Windows.Forms.Label();
            this.freshmanRadioButton = new System.Windows.Forms.RadioButton();
            this.sophomoreRadioButton = new System.Windows.Forms.RadioButton();
            this.juniorRadioButton = new System.Windows.Forms.RadioButton();
            this.seniorRadioButton = new System.Windows.Forms.RadioButton();
            this.universityComboBox = new System.Windows.Forms.ComboBox();
            this.majorListBox = new System.Windows.Forms.ListBox();
            this.lastNameTextBox = new System.Windows.Forms.TextBox();
            this.firstNameTextBox = new System.Windows.Forms.TextBox();
            this.studentIDTextBox = new System.Windows.Forms.TextBox();
            this.deansListCheckBox = new System.Windows.Forms.CheckBox();
            this.universityLabel = new System.Windows.Forms.Label();
            this.majorLabel = new System.Windows.Forms.Label();
            this.lastNameLabel = new System.Windows.Forms.Label();
            this.firstNameLabel = new System.Windows.Forms.Label();
            this.studentIDLabel = new System.Windows.Forms.Label();
            this.okButton = new System.Windows.Forms.Button();
            this.clearButton = new System.Windows.Forms.Button();
            this.studentDataMainFormToolTip = new System.Windows.Forms.ToolTip(this.components);
            this.studentDataMainFormMenuStrip.SuspendLayout();
            this.addAStudentGroupBox.SuspendLayout();
            this.standingGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // studentDataMainFormMenuStrip
            // 
            this.studentDataMainFormMenuStrip.BackColor = System.Drawing.SystemColors.Control;
            this.studentDataMainFormMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.editToolStripMenuItem,
            this.helpToolStripMenuItem});
            this.studentDataMainFormMenuStrip.Location = new System.Drawing.Point(0, 0);
            this.studentDataMainFormMenuStrip.Name = "studentDataMainFormMenuStrip";
            this.studentDataMainFormMenuStrip.Size = new System.Drawing.Size(590, 24);
            this.studentDataMainFormMenuStrip.TabIndex = 0;
            this.studentDataMainFormMenuStrip.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.showAllStudentsToolStripMenuItem,
            this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "&File";
            // 
            // showAllStudentsToolStripMenuItem
            // 
            this.showAllStudentsToolStripMenuItem.Name = "showAllStudentsToolStripMenuItem";
            this.showAllStudentsToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.A)));
            this.showAllStudentsToolStripMenuItem.Size = new System.Drawing.Size(213, 22);
            this.showAllStudentsToolStripMenuItem.Text = "Show &all students...";
            this.showAllStudentsToolStripMenuItem.Click += new System.EventHandler(this.showAllStudentsToolStripMenuItem_Click);
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.F4)));
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(213, 22);
            this.exitToolStripMenuItem.Text = "E&xit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.exitToolStripMenuItem_Click);
            // 
            // editToolStripMenuItem
            // 
            this.editToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.addUniversityToolStripMenuItem});
            this.editToolStripMenuItem.Name = "editToolStripMenuItem";
            this.editToolStripMenuItem.Size = new System.Drawing.Size(39, 20);
            this.editToolStripMenuItem.Text = "&Edit";
            // 
            // addUniversityToolStripMenuItem
            // 
            this.addUniversityToolStripMenuItem.Name = "addUniversityToolStripMenuItem";
            this.addUniversityToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.addUniversityToolStripMenuItem.Text = "Add &University...";
            this.addUniversityToolStripMenuItem.Click += new System.EventHandler(this.addUniversityToolStripMenuItem_Click);
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.aboutToolStripMenuItem});
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.helpToolStripMenuItem.Text = "&Help";
            // 
            // aboutToolStripMenuItem
            // 
            this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            this.aboutToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.F1)));
            this.aboutToolStripMenuItem.Size = new System.Drawing.Size(153, 22);
            this.aboutToolStripMenuItem.Text = "&About";
            this.aboutToolStripMenuItem.Click += new System.EventHandler(this.aboutToolStripMenuItem_Click);
            // 
            // addAStudentGroupBox
            // 
            this.addAStudentGroupBox.Controls.Add(this.standingGroupBox);
            this.addAStudentGroupBox.Controls.Add(this.universityComboBox);
            this.addAStudentGroupBox.Controls.Add(this.majorListBox);
            this.addAStudentGroupBox.Controls.Add(this.lastNameTextBox);
            this.addAStudentGroupBox.Controls.Add(this.firstNameTextBox);
            this.addAStudentGroupBox.Controls.Add(this.studentIDTextBox);
            this.addAStudentGroupBox.Controls.Add(this.deansListCheckBox);
            this.addAStudentGroupBox.Controls.Add(this.universityLabel);
            this.addAStudentGroupBox.Controls.Add(this.majorLabel);
            this.addAStudentGroupBox.Controls.Add(this.lastNameLabel);
            this.addAStudentGroupBox.Controls.Add(this.firstNameLabel);
            this.addAStudentGroupBox.Controls.Add(this.studentIDLabel);
            this.addAStudentGroupBox.Location = new System.Drawing.Point(12, 27);
            this.addAStudentGroupBox.Name = "addAStudentGroupBox";
            this.addAStudentGroupBox.Size = new System.Drawing.Size(566, 298);
            this.addAStudentGroupBox.TabIndex = 1;
            this.addAStudentGroupBox.TabStop = false;
            this.addAStudentGroupBox.Text = "Add a student";
            // 
            // standingGroupBox
            // 
            this.standingGroupBox.Controls.Add(this.standingLabel);
            this.standingGroupBox.Controls.Add(this.freshmanRadioButton);
            this.standingGroupBox.Controls.Add(this.sophomoreRadioButton);
            this.standingGroupBox.Controls.Add(this.juniorRadioButton);
            this.standingGroupBox.Controls.Add(this.seniorRadioButton);
            this.standingGroupBox.Location = new System.Drawing.Point(279, 75);
            this.standingGroupBox.Name = "standingGroupBox";
            this.standingGroupBox.Size = new System.Drawing.Size(281, 115);
            this.standingGroupBox.TabIndex = 10;
            this.standingGroupBox.TabStop = false;
            // 
            // standingLabel
            // 
            this.standingLabel.AutoSize = true;
            this.standingLabel.Location = new System.Drawing.Point(19, 18);
            this.standingLabel.Name = "standingLabel";
            this.standingLabel.Size = new System.Drawing.Size(59, 15);
            this.standingLabel.TabIndex = 0;
            this.standingLabel.Text = "Standing:";
            // 
            // freshmanRadioButton
            // 
            this.freshmanRadioButton.AutoSize = true;
            this.freshmanRadioButton.Location = new System.Drawing.Point(142, 17);
            this.freshmanRadioButton.Name = "freshmanRadioButton";
            this.freshmanRadioButton.Size = new System.Drawing.Size(81, 19);
            this.freshmanRadioButton.TabIndex = 1;
            this.freshmanRadioButton.TabStop = true;
            this.freshmanRadioButton.Text = "Freshman";
            this.freshmanRadioButton.UseVisualStyleBackColor = true;
            // 
            // sophomoreRadioButton
            // 
            this.sophomoreRadioButton.AutoSize = true;
            this.sophomoreRadioButton.Location = new System.Drawing.Point(142, 39);
            this.sophomoreRadioButton.Name = "sophomoreRadioButton";
            this.sophomoreRadioButton.Size = new System.Drawing.Size(90, 19);
            this.sophomoreRadioButton.TabIndex = 2;
            this.sophomoreRadioButton.TabStop = true;
            this.sophomoreRadioButton.Text = "Sophomore";
            this.sophomoreRadioButton.UseVisualStyleBackColor = true;
            // 
            // juniorRadioButton
            // 
            this.juniorRadioButton.AutoSize = true;
            this.juniorRadioButton.Location = new System.Drawing.Point(142, 61);
            this.juniorRadioButton.Name = "juniorRadioButton";
            this.juniorRadioButton.Size = new System.Drawing.Size(59, 19);
            this.juniorRadioButton.TabIndex = 3;
            this.juniorRadioButton.TabStop = true;
            this.juniorRadioButton.Text = "Junior";
            this.juniorRadioButton.UseVisualStyleBackColor = true;
            // 
            // seniorRadioButton
            // 
            this.seniorRadioButton.AutoSize = true;
            this.seniorRadioButton.Location = new System.Drawing.Point(142, 83);
            this.seniorRadioButton.Name = "seniorRadioButton";
            this.seniorRadioButton.Size = new System.Drawing.Size(61, 19);
            this.seniorRadioButton.TabIndex = 4;
            this.seniorRadioButton.TabStop = true;
            this.seniorRadioButton.Text = "Senior";
            this.seniorRadioButton.UseVisualStyleBackColor = true;
            // 
            // universityComboBox
            // 
            this.universityComboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.universityComboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.universityComboBox.FormattingEnabled = true;
            this.universityComboBox.Location = new System.Drawing.Point(347, 38);
            this.universityComboBox.Name = "universityComboBox";
            this.universityComboBox.Size = new System.Drawing.Size(213, 23);
            this.universityComboBox.TabIndex = 9;
            // 
            // majorListBox
            // 
            this.majorListBox.FormattingEnabled = true;
            this.majorListBox.ItemHeight = 15;
            this.majorListBox.Location = new System.Drawing.Point(87, 126);
            this.majorListBox.Name = "majorListBox";
            this.majorListBox.Size = new System.Drawing.Size(167, 154);
            this.majorListBox.TabIndex = 7;
            // 
            // lastNameTextBox
            // 
            this.lastNameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.lastNameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.lastNameTextBox.Location = new System.Drawing.Point(87, 98);
            this.lastNameTextBox.Name = "lastNameTextBox";
            this.lastNameTextBox.Size = new System.Drawing.Size(120, 21);
            this.lastNameTextBox.TabIndex = 5;
            // 
            // firstNameTextBox
            // 
            this.firstNameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.firstNameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.firstNameTextBox.Location = new System.Drawing.Point(87, 69);
            this.firstNameTextBox.Name = "firstNameTextBox";
            this.firstNameTextBox.Size = new System.Drawing.Size(120, 21);
            this.firstNameTextBox.TabIndex = 3;
            // 
            // studentIDTextBox
            // 
            this.studentIDTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.studentIDTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.studentIDTextBox.Location = new System.Drawing.Point(87, 39);
            this.studentIDTextBox.MaxLength = 9;
            this.studentIDTextBox.Name = "studentIDTextBox";
            this.studentIDTextBox.Size = new System.Drawing.Size(120, 21);
            this.studentIDTextBox.TabIndex = 1;
            this.studentDataMainFormToolTip.SetToolTip(this.studentIDTextBox, "Student ID must be in the form  \"UxxxNxxxx\" where every \'x\' represents a digit 0-" +
        "9.");
            this.studentIDTextBox.TextChanged += new System.EventHandler(this.studentIDTextBox_TextChanged);
            // 
            // deansListCheckBox
            // 
            this.deansListCheckBox.AutoSize = true;
            this.deansListCheckBox.Location = new System.Drawing.Point(382, 205);
            this.deansListCheckBox.Name = "deansListCheckBox";
            this.deansListCheckBox.Size = new System.Drawing.Size(83, 19);
            this.deansListCheckBox.TabIndex = 11;
            this.deansListCheckBox.Text = "Dean\'s list";
            this.studentDataMainFormToolTip.SetToolTip(this.deansListCheckBox, "GPA >= 3.5/4.0");
            this.deansListCheckBox.UseVisualStyleBackColor = true;
            // 
            // universityLabel
            // 
            this.universityLabel.AutoSize = true;
            this.universityLabel.Location = new System.Drawing.Point(276, 41);
            this.universityLabel.Name = "universityLabel";
            this.universityLabel.Size = new System.Drawing.Size(62, 15);
            this.universityLabel.TabIndex = 8;
            this.universityLabel.Text = "University:";
            // 
            // majorLabel
            // 
            this.majorLabel.AutoSize = true;
            this.majorLabel.Location = new System.Drawing.Point(36, 126);
            this.majorLabel.Name = "majorLabel";
            this.majorLabel.Size = new System.Drawing.Size(42, 15);
            this.majorLabel.TabIndex = 6;
            this.majorLabel.Text = "Major:";
            // 
            // lastNameLabel
            // 
            this.lastNameLabel.AutoSize = true;
            this.lastNameLabel.Location = new System.Drawing.Point(10, 98);
            this.lastNameLabel.Name = "lastNameLabel";
            this.lastNameLabel.Size = new System.Drawing.Size(68, 15);
            this.lastNameLabel.TabIndex = 4;
            this.lastNameLabel.Text = "Last name:";
            // 
            // firstNameLabel
            // 
            this.firstNameLabel.AutoSize = true;
            this.firstNameLabel.Location = new System.Drawing.Point(12, 69);
            this.firstNameLabel.Name = "firstNameLabel";
            this.firstNameLabel.Size = new System.Drawing.Size(68, 15);
            this.firstNameLabel.TabIndex = 2;
            this.firstNameLabel.Text = "First name:";
            // 
            // studentIDLabel
            // 
            this.studentIDLabel.AutoSize = true;
            this.studentIDLabel.Location = new System.Drawing.Point(12, 41);
            this.studentIDLabel.Name = "studentIDLabel";
            this.studentIDLabel.Size = new System.Drawing.Size(67, 15);
            this.studentIDLabel.TabIndex = 0;
            this.studentIDLabel.Text = "Student ID:";
            this.studentDataMainFormToolTip.SetToolTip(this.studentIDLabel, "Student ID must be in the form \"UxxxNxxxx\" where every \'x\' represents a digit 0-9" +
        ".");
            // 
            // okButton
            // 
            this.okButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.okButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.okButton.Location = new System.Drawing.Point(320, 331);
            this.okButton.Name = "okButton";
            this.okButton.Size = new System.Drawing.Size(87, 22);
            this.okButton.TabIndex = 3;
            this.okButton.Text = "&OK";
            this.studentDataMainFormToolTip.SetToolTip(this.okButton, "Add the entry for this student to the database");
            this.okButton.Click += new System.EventHandler(this.okButton_Click);
            // 
            // clearButton
            // 
            this.clearButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.clearButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.clearButton.Location = new System.Drawing.Point(173, 331);
            this.clearButton.Name = "clearButton";
            this.clearButton.Size = new System.Drawing.Size(87, 22);
            this.clearButton.TabIndex = 2;
            this.clearButton.Text = "&Clear";
            this.clearButton.Click += new System.EventHandler(this.clearButton_Click);
            // 
            // StudentDataMainForm
            // 
            this.AcceptButton = this.okButton;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(590, 359);
            this.Controls.Add(this.clearButton);
            this.Controls.Add(this.okButton);
            this.Controls.Add(this.addAStudentGroupBox);
            this.Controls.Add(this.studentDataMainFormMenuStrip);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = global::StudentData.Properties.Resources._1479572520_app_type_university_512px_GREY;
            this.MainMenuStrip = this.studentDataMainFormMenuStrip;
            this.MaximizeBox = false;
            this.Name = "StudentDataMainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Student Data";
            this.studentDataMainFormMenuStrip.ResumeLayout(false);
            this.studentDataMainFormMenuStrip.PerformLayout();
            this.addAStudentGroupBox.ResumeLayout(false);
            this.addAStudentGroupBox.PerformLayout();
            this.standingGroupBox.ResumeLayout(false);
            this.standingGroupBox.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip studentDataMainFormMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem showAllStudentsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem addUniversityToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.GroupBox addAStudentGroupBox;
        private System.Windows.Forms.Button okButton;
        private System.Windows.Forms.ToolTip studentDataMainFormToolTip;
        private System.Windows.Forms.Button clearButton;
        private System.Windows.Forms.Label standingLabel;
        private System.Windows.Forms.ComboBox universityComboBox;
        private System.Windows.Forms.ListBox majorListBox;
        private System.Windows.Forms.TextBox lastNameTextBox;
        private System.Windows.Forms.TextBox firstNameTextBox;
        private System.Windows.Forms.TextBox studentIDTextBox;
        private System.Windows.Forms.RadioButton freshmanRadioButton;
        private System.Windows.Forms.RadioButton sophomoreRadioButton;
        private System.Windows.Forms.RadioButton juniorRadioButton;
        private System.Windows.Forms.RadioButton seniorRadioButton;
        private System.Windows.Forms.CheckBox deansListCheckBox;
        private System.Windows.Forms.Label universityLabel;
        private System.Windows.Forms.Label majorLabel;
        private System.Windows.Forms.Label lastNameLabel;
        private System.Windows.Forms.Label firstNameLabel;
        private System.Windows.Forms.Label studentIDLabel;
        private System.Windows.Forms.GroupBox standingGroupBox;
    }
}